[terminal]
shell = { program = "wsl.exe", args = ["~"] }

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
#padding = { x = 15, y = 15 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16

[general]
import = ["catppuccin-mocha.toml"]

[selection]
save_to_clipboard = true
